spring.application.name=user-service

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/user-service
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Performance tuning parameters
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect